# Generated by Django 4.1.2 on 2022-10-22 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalPostion',
            new_name='DepartmentPersonalPostion',
        ),
    ]
