# Generated by Django 4.1.2 on 2022-10-23 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_alter_department_supervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaltask',
            old_name='notify_at',
            new_name='deadline_at',
        ),
    ]
